name: Test
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: "npm"
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Start Docker services
        run: docker-compose up -d
      - name: composer install
        run: docker-compose exec -T php bash -c "composer install"
      - name: Run PHPUnit
        run: docker-compose exec -T php bash -c "php vendor/bin/phpunit"
